### ISSUE TITLE
Create UserHeader

### ISSUE THREAD

**Issue by nicknapoli82** [1904-cpu-projects/errant-outfitters#48]
This component exists. It needs 
A login form (email, password) and submit button
This can be a very dumb form. 

When user is logged in, this component only renders a logout button

**Comment by roboMoose** [comment]
Schuyler agreed to take over the User slice.

**Comment by nicknapoli82** [comment]
Hey @skythrilla. You are welcome to change the name of the UserHeader component if you want. I originally just made up a name, but if you think there is something more meaningful that you want to use go for it.
