### ISSUE TITLE
Correct server instance issue in test file

### ISSUE THREAD

**Issue by roboMoose** [1904-cpu-projects/errant-outfitters#54]
I was going to do this in my current branch, but I think it is better as a separate issue:

Based on Eliot's comments, switch out the listening server for a fresh server instance. Add db.sync() and db.close() to beforeAll and afterAll life-cycle methods

**Comment by roboMoose** [comment]
I will crush this bug if it's the last thing i do!

**Comment by nicknapoli82** [comment]
LOL. 
Sorry man. I put up that jest issue on our slack channel thinking that was enough information.
