### ISSUE TITLE
finalize db/models

### ISSUE THREAD

**Issue by roboMoose** [1904-cpu-projects/errant-outfitters#6]
Group effort - Laying down a good foundation for moving forward.

**Comment by SamOlivas** [comment]
**Product:** 
Default photo route if none included
**Users:**
Validation: isEmail, isUnique
Prop added: isAdmin (default value: false), firstName, lastName
**Transaction:**
Associations updated: see pics
**Review:**
New model
Associations: User.hasMany(Review), Product.hasMany(Review)
Validation: length 10-250 chars
**Associations (total rework, see wiki/resource/DBvisual)**

**Todo - Validation Feedback for User:**
User - email not email, email not unique
Review - body too short/long (acceptable = 10-250 chars)
